### ISSUE TITLE
修改代码块空行的规则

### ISSUE THREAD

**Issue by moonRider** [Byzanteam/jet-linter#9]
- [x] 多行变量声明应有空行
- [x] 多个变量声明语句不应有空行
- [x] if，block，function 前后应有空行
- [x] 表达式与变量声明间应有空行
- [x] 最后一个 import 后面应有空行
- [x] vue 的 block 之间应有空行

**Comment by fahchen** [comment]
你 assihn 给我俩干啥呀？

**Comment by moonRider** [comment]
... 点错了，reviewer
